// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3p6UxcIlIfW93JE35HYnO1Ka2FtHyhA',
    appId: '1:535735125644:web:72585da9690d208e1f1da9',
    messagingSenderId: '535735125644',
    projectId: 'hamfins-719b8',
    authDomain: 'hamfins-719b8.firebaseapp.com',
    storageBucket: 'hamfins-719b8.firebasestorage.app',
    measurementId: 'G-41SY771Y7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjegrT2ZKH_739vuGTF8-buRwFUAmdskQ',
    appId: '1:535735125644:android:43efdb7022d3884c1f1da9',
    messagingSenderId: '535735125644',
    projectId: 'hamfins-719b8',
    storageBucket: 'hamfins-719b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8aZ5DGYvM08WMuJmipkCk-TnUGy9BcM',
    appId: '1:535735125644:ios:b61ad3c3038da7521f1da9',
    messagingSenderId: '535735125644',
    projectId: 'hamfins-719b8',
    storageBucket: 'hamfins-719b8.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3p6UxcIlIfW93JE35HYnO1Ka2FtHyhA',
    appId: '1:535735125644:web:619b3b967954b8d91f1da9',
    messagingSenderId: '535735125644',
    projectId: 'hamfins-719b8',
    authDomain: 'hamfins-719b8.firebaseapp.com',
    storageBucket: 'hamfins-719b8.firebasestorage.app',
    measurementId: 'G-YSS9HCD5RF',
  );
}
